### ISSUE TITLE
Add a method to walk towards a position until the character is within a certain radius

### ISSUE THREAD

**Issue by Gilgames000** [Roxeez/Moonlight#9]
I was thinking about adding a method that lets your character walk towards a position until it's within a certain radius around it. For example, it'd be useful if you want to use a skill with a range higher than one cell (e.g. mage/archer base attack) instead of `Walk`ing to the monster position.
One way would be to add the following method to the `Character` class:

```c#
public async Task WalkUntilInRadius(Position destination, int radius)
{
    int distance = Position.GetDistance(destination);
    if (distance <= radius)
    {
        return;
    }

    double distRatio = (distance - radius) / (double)distance;
    double x = Position.X + distRatio * (destination.X - Position.X);
    double y = Position.Y + distRatio * (destination.Y - Position.Y);

    await Walk(new Position((short)x, (short)y));
}
```

Then, instead of doing this
```c#
if (monster.Position.GetDistance(character.Position) > skill.Info.Range)
{
    await character.Walk(monster.Position);
 }
```
you just need this
```c#
await character.WalkUntilInRadius(monster.Position, skill.Info.Range);
```

I don't know if I explained in a good way the purpose of the above method. In case I didn't, I'll leave [here](https://i.imgur.com/fdwMxLW.png) an image made with my pr0 design skills™ that should explain it.

Cheers!

**Comment by Roxeez** [comment]
Good idea, gonna add it when i can :)

**Comment by Roxeez** [comment]
Done in #12
